/**
 * Voice Note Analysis Component
 * 
 * Handles transcription and AI analysis of voice recordings
 */

import React, { useState } from "react";
import { View, Text, TouchableOpacity, ActivityIndicator, Share, Alert } from "react-native";
import { trpc } from "@/lib/trpc";
import { readFileAsBase64, getFileNameFromUri } from "@/lib/s3-upload";
import { getEmotionEmoji, getEnergyLevelColor } from "@/lib/voice-journal-integration";
import * as Haptics from "expo-haptics";
import * as Clipboard from "expo-clipboard";

interface VoiceNoteAnalysisProps {
  voiceNoteUri: string;
  voiceNoteId: string;
  energyScore?: number;
}

interface AnalysisResult {
  transcription: string;
  language: string;
  emotionalTone: string;
  emotions: string[];
  energyLevel: string;
  themes: string[];
  insight: string;
}

export function VoiceNoteAnalysis({ voiceNoteUri, voiceNoteId, energyScore }: VoiceNoteAnalysisProps) {
  const [analyzing, setAnalyzing] = useState(false);
  const [analysis, setAnalysis] = useState<AnalysisResult | null>(null);
  const [error, setError] = useState<string | null>(null);

  const uploadMutation = trpc.upload.uploadFile.useMutation();
  const transcribeMutation = trpc.voiceJournal.transcribeAudio.useMutation();
  const analyzeMutation = trpc.voiceJournal.analyzeJournalEntry.useMutation();

  const handleAnalyze = async () => {
    try {
      setAnalyzing(true);
      setError(null);
      await Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);

      // Step 1: Read file as base64
      const base64Data = await readFileAsBase64(voiceNoteUri);
      const fileName = getFileNameFromUri(voiceNoteUri);

      // Step 2: Upload to S3
      const uploadResult = await uploadMutation.mutateAsync({
        fileData: base64Data,
        fileName,
        mimeType: "audio/m4a",
      });

      if (!uploadResult.success || !uploadResult.url) {
        throw new Error("Failed to upload audio file");
      }

      // Step 3: Transcribe with Whisper
      const transcriptionResult = await transcribeMutation.mutateAsync({
        audioUrl: uploadResult.url,
      });

      if (!transcriptionResult.success || !transcriptionResult.transcription) {
        throw new Error("Failed to transcribe audio");
      }

      // Step 4: Analyze with AI
      const today = new Date().toISOString().split("T")[0];
      const analysisResult = await analyzeMutation.mutateAsync({
        text: transcriptionResult.transcription,
        date: today,
        energyScore,
      });

      if (!analysisResult.success || !analysisResult.analysis) {
        throw new Error("Failed to analyze journal entry");
      }

      // Store result
      setAnalysis({
        transcription: transcriptionResult.transcription,
        language: transcriptionResult.language,
        ...analysisResult.analysis,
      });

      await Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success);
    } catch (err) {
      console.error("Analysis error:", err);
      setError(err instanceof Error ? err.message : "Analysis failed");
      await Haptics.notificationAsync(Haptics.NotificationFeedbackType.Error);
    } finally {
      setAnalyzing(false);
    }
  };

  const handleShare = async () => {
    if (!analysis) return;
    
    try {
      await Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);
      
      const shareText = `🎤 Voice Note Analysis\n\n` +
        `📝 TRANSCRIPTION:\n${analysis.transcription}\n\n` +
        `${getEmotionEmoji(analysis.emotionalTone)} EMOTIONAL TONE: ${analysis.emotionalTone}\n` +
        `⚡ ENERGY LEVEL: ${analysis.energyLevel}\n\n` +
        `😊 EMOTIONS: ${analysis.emotions.join(", ")}\n\n` +
        `🏷️ THEMES: ${analysis.themes.join(", ")}\n\n` +
        `💡 AI INSIGHT:\n${analysis.insight}\n\n` +
        `🌐 Language: ${analysis.language}\n\n` +
        `Generated by Energy Today`;
      
      await Share.share({
        message: shareText,
        title: "Voice Note Analysis",
      });
    } catch (error) {
      console.error("Share error:", error);
    }
  };

  const handleCopyToClipboard = async () => {
    if (!analysis) return;
    
    try {
      await Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);
      
      const copyText = `Voice Note Analysis\n\n` +
        `Transcription: ${analysis.transcription}\n\n` +
        `Emotional Tone: ${analysis.emotionalTone}\n` +
        `Energy Level: ${analysis.energyLevel}\n` +
        `Emotions: ${analysis.emotions.join(", ")}\n` +
        `Themes: ${analysis.themes.join(", ")}\n\n` +
        `AI Insight: ${analysis.insight}`;
      
      await Clipboard.setStringAsync(copyText);
      Alert.alert("Copied!", "Analysis copied to clipboard");
      await Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success);
    } catch (error) {
      console.error("Copy error:", error);
      Alert.alert("Error", "Failed to copy to clipboard");
    }
  };

  if (analysis) {
    return (
      <View className="bg-primary/5 rounded-lg p-3 gap-2 mt-2">
        {/* Transcription */}
        <View>
          <Text className="text-xs font-medium text-muted mb-1">TRANSCRIPTION</Text>
          <Text className="text-sm text-foreground">{analysis.transcription}</Text>
        </View>

        {/* Emotional Analysis */}
        <View className="flex-row items-center gap-2">
          <Text className="text-2xl">{getEmotionEmoji(analysis.emotionalTone)}</Text>
          <View className="flex-1">
            <Text className="text-xs font-medium text-muted">EMOTIONAL TONE</Text>
            <Text className="text-sm text-foreground capitalize">{analysis.emotionalTone}</Text>
          </View>
          <View
            className="px-2 py-1 rounded"
            style={{ backgroundColor: getEnergyLevelColor(analysis.energyLevel) + "20" }}
          >
            <Text
              className="text-xs font-medium"
              style={{ color: getEnergyLevelColor(analysis.energyLevel) }}
            >
              {analysis.energyLevel.toUpperCase()}
            </Text>
          </View>
        </View>

        {/* Emotions */}
        {analysis.emotions.length > 0 && (
          <View>
            <Text className="text-xs font-medium text-muted mb-1">EMOTIONS</Text>
            <View className="flex-row flex-wrap gap-1">
              {analysis.emotions.map((emotion, index) => (
                <View key={index} className="bg-primary/10 px-2 py-1 rounded">
                  <Text className="text-xs text-primary capitalize">{emotion}</Text>
                </View>
              ))}
            </View>
          </View>
        )}

        {/* Themes */}
        {analysis.themes.length > 0 && (
          <View>
            <Text className="text-xs font-medium text-muted mb-1">THEMES</Text>
            <View className="flex-row flex-wrap gap-1">
              {analysis.themes.map((theme, index) => (
                <View key={index} className="bg-surface px-2 py-1 rounded border border-border">
                  <Text className="text-xs text-foreground capitalize">{theme}</Text>
                </View>
              ))}
            </View>
          </View>
        )}

        {/* AI Insight */}
        <View className="bg-primary/10 rounded p-2">
          <Text className="text-xs font-medium text-primary mb-1">💡 AI INSIGHT</Text>
          <Text className="text-sm text-foreground">{analysis.insight}</Text>
        </View>

        {/* Language */}
        <Text className="text-xs text-muted text-right">
          Language: {analysis.language.toUpperCase()}
        </Text>
        
        {/* Share Actions */}
        <View className="flex-row gap-2 mt-2">
          <TouchableOpacity
            onPress={handleShare}
            className="flex-1 bg-primary py-2 rounded-lg flex-row items-center justify-center gap-2"
          >
            <Text className="text-lg">🔗</Text>
            <Text className="text-white font-medium text-sm">Share</Text>
          </TouchableOpacity>
          
          <TouchableOpacity
            onPress={handleCopyToClipboard}
            className="flex-1 bg-surface border border-border py-2 rounded-lg flex-row items-center justify-center gap-2"
          >
            <Text className="text-lg">📋</Text>
            <Text className="text-foreground font-medium text-sm">Copy</Text>
          </TouchableOpacity>
        </View>
      </View>
    );
  }

  if (error) {
    return (
      <View className="bg-error/10 rounded-lg p-3 mt-2">
        <Text className="text-sm text-error">{error}</Text>
        <TouchableOpacity
          onPress={handleAnalyze}
          className="bg-error/20 px-3 py-2 rounded mt-2"
        >
          <Text className="text-xs text-error font-medium text-center">Try Again</Text>
        </TouchableOpacity>
      </View>
    );
  }

  return (
    <TouchableOpacity
      onPress={handleAnalyze}
      disabled={analyzing}
      className="bg-primary/10 rounded-lg p-3 mt-2 flex-row items-center justify-center gap-2"
    >
      {analyzing ? (
        <>
          <ActivityIndicator size="small" color="#0A7EA4" />
          <Text className="text-sm text-primary font-medium">Analyzing...</Text>
        </>
      ) : (
        <>
          <Text className="text-lg">🤖</Text>
          <Text className="text-sm text-primary font-medium">Analyze with AI</Text>
        </>
      )}
    </TouchableOpacity>
  );
}
