import { describe, it, expect } from "vitest";

describe("Voice Notes", () => {
  it("should format duration correctly", () => {
    const formatDuration = (ms: number) => {
      const seconds = Math.floor(ms / 1000);
      const minutes = Math.floor(seconds / 60);
      const remainingSeconds = seconds % 60;
      return `${minutes}:${remainingSeconds.toString().padStart(2, "0")}`;
    };
    
    expect(formatDuration(0)).toBe("0:00");
    expect(formatDuration(5000)).toBe("0:05");
    expect(formatDuration(60000)).toBe("1:00");
    expect(formatDuration(125000)).toBe("2:05");
    expect(formatDuration(3661000)).toBe("61:01");
  });
});

describe("Weekly Planning", () => {
  it("should generate 7-day forecast structure", () => {
    const forecast = Array.from({ length: 7 }, (_, i) => ({
      date: new Date(Date.now() + i * 24 * 60 * 60 * 1000).toISOString(),
      alignmentScore: 50 + Math.random() * 50,
      alignment: "moderate" as const,
    }));
    
    expect(forecast).toHaveLength(7);
    expect(forecast[0]).toHaveProperty("date");
    expect(forecast[0]).toHaveProperty("alignmentScore");
    expect(forecast[0]).toHaveProperty("alignment");
  });
});

describe("Sharing Features", () => {
  it("should format date for sharing", () => {
    const date = new Date("2024-01-15T12:00:00Z");
    const formatted = date.toLocaleDateString("en-US", {
      weekday: "long",
      year: "numeric",
      month: "long",
      day: "numeric",
      timeZone: "UTC",
    });
    expect(formatted).toBe("Monday, January 15, 2024");
  });

  it("should generate share text with proper structure", () => {
    const shareText = `Energy Today Summary

Date: Monday, January 15, 2024
User Energy: 85%
Today's Energy: 72%
Alignment: Strong (90%)

Connection: Your high creative energy aligns beautifully with today's momentum.

Generated by Energy Today`;

    expect(shareText).toContain("Energy Today Summary");
    expect(shareText).toContain("User Energy:");
    expect(shareText).toContain("Today's Energy:");
    expect(shareText).toContain("Alignment:");
  });
});
