import * as Sharing from "expo-sharing";
import * as FileSystem from "expo-file-system/legacy";
import { UserProfile, DailyEnergy } from "@/types";
import { TrendAnalysis } from "./energy-trends";
import { TeamSyncAnalysis } from "./team-sync";

/**
 * Generate a shareable text summary of energy data
 */
export function generateEnergySummary(
  profile: UserProfile,
  energy: DailyEnergy,
  date: Date
): string {
  const dateStr = date.toLocaleDateString("en-US", {
    weekday: "long",
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  return `Energy Today - ${dateStr}

${profile.name}'s Energy Profile
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

YOUR ENERGY: ${energy.userEnergy.type}
Intensity: ${energy.userEnergy.intensity}%
${energy.userEnergy.description}

TODAY'S ENERGY: ${energy.environmentalEnergy.type}
Intensity: ${energy.environmentalEnergy.intensity}%
${energy.environmentalEnergy.description}

THE CONNECTION: ${energy.connection.alignment.toUpperCase()}
${energy.connection.summary}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Generated by Energy Today app`;
}

/**
 * Generate a shareable weekly summary
 */
export function generateWeeklySummary(
  profile: UserProfile,
  trends: TrendAnalysis
): string {
  const bestDaysStr = trends.bestDays
    .map((d) =>
      new Date(d).toLocaleDateString("en-US", { month: "short", day: "numeric" })
    )
    .join(", ");

  const challengingDaysStr = trends.challengingDays
    .map((d) =>
      new Date(d).toLocaleDateString("en-US", { month: "short", day: "numeric" })
    )
    .join(", ");

  return `Energy Today - Weekly Summary

${profile.name}'s Energy Trends
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

AVERAGES
• Your Energy: ${trends.averageUserEnergy}%
• Earth Energy: ${trends.averageEnvironmentalEnergy}%
• Alignment: ${trends.averageAlignment}%

BEST DAYS (${trends.bestDays.length})
${bestDaysStr || "None this week"}

CHALLENGING DAYS (${trends.challengingDays.length})
${challengingDaysStr || "None this week"}

INSIGHTS
${trends.insights.map((insight, i) => `${i + 1}. ${insight}`).join("\n")}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Generated by Energy Today app`;
}

/**
 * Share energy summary as text
 */
export async function shareEnergySummary(
  profile: UserProfile,
  energy: DailyEnergy,
  date: Date
): Promise<void> {
  const summary = generateEnergySummary(profile, energy, date);
  const fileName = `energy-${date.toISOString().split("T")[0]}.txt`;
  const fileUri = `${FileSystem.cacheDirectory ?? ""}${fileName}`;

  await FileSystem.writeAsStringAsync(fileUri, summary);

  if (await Sharing.isAvailableAsync()) {
    await Sharing.shareAsync(fileUri, {
      mimeType: "text/plain",
      dialogTitle: "Share Energy Summary",
    });
  } else {
    throw new Error("Sharing is not available on this device");
  }
}

/**
 * Share weekly trends summary
 */
export async function shareWeeklySummary(
  profile: UserProfile,
  trends: TrendAnalysis
): Promise<void> {
  const summary = generateWeeklySummary(profile, trends);
  const fileName = `energy-weekly-${new Date().toISOString().split("T")[0]}.txt`;
  const fileUri = `${FileSystem.cacheDirectory ?? ""}${fileName}`;

  await FileSystem.writeAsStringAsync(fileUri, summary);

  if (await Sharing.isAvailableAsync()) {
    await Sharing.shareAsync(fileUri, {
      mimeType: "text/plain",
      dialogTitle: "Share Weekly Summary",
    });
  } else {
    throw new Error("Sharing is not available on this device");
  }
}

/**
 * Share calendar view (uses existing PDF export)
 */
export async function shareCalendarView(pdfPath: string): Promise<void> {
  if (await Sharing.isAvailableAsync()) {
    await Sharing.shareAsync(pdfPath, {
      mimeType: "application/pdf",
      dialogTitle: "Share Calendar",
    });
  } else {
    throw new Error("Sharing is not available on this device");
  }
}

/**
 * Generate a simple shareable image of energy data
 * (This is a simplified version - in production, you might use canvas or SVG)
 */
export async function generateShareableImage(
  profile: UserProfile,
  energy: DailyEnergy,
  date: Date
): Promise<string> {
  // For now, we'll create a rich text file that can be shared
  // In a full implementation, you could use react-native-view-shot or similar
  const content = generateEnergySummary(profile, energy, date);
  const fileName = `energy-share-${date.toISOString().split("T")[0]}.txt`;
  const fileUri = `${FileSystem.cacheDirectory ?? ""}${fileName}`;

  await FileSystem.writeAsStringAsync(fileUri, content);
  return fileUri;
}

/**
 * Share team energy sync results
 */
export async function shareEnergySync(
  userName: string,
  partnerName: string,
  analysis: TeamSyncAnalysis
): Promise<void> {
  const bestDate = new Date(analysis.bestMeetingTime.date).toLocaleDateString("en-US", {
    weekday: "long",
    month: "long",
    day: "numeric",
  });

  const shareText = `Team Energy Sync: ${userName} & ${partnerName}

Best Meeting Time: ${bestDate}
${analysis.bestMeetingTime.reason}

Next 14 Days:
🟢 Optimal: ${analysis.optimalDays.length} days
🟡 Good: ${analysis.goodDays.length} days
🔴 Avoid: ${analysis.avoidDays.length} days

Insights:
${analysis.insights.map((i) => `• ${i}`).join("\n")}

Generated by Energy Today`;

  const fileName = `team-sync-${new Date().toISOString().split("T")[0]}.txt`;
  const fileUri = `${FileSystem.cacheDirectory ?? ""}${fileName}`;

  await FileSystem.writeAsStringAsync(fileUri, shareText);

  if (await Sharing.isAvailableAsync()) {
    await Sharing.shareAsync(fileUri, {
      mimeType: "text/plain",
      dialogTitle: "Share Team Energy Sync",
    });
  } else {
    throw new Error("Sharing is not available on this device");
  }
}
